### ISSUE TITLE
Displaying Sales Comps

### ISSUE THREAD

**Issue by erhla** [erhla/ptap#14]
Adding Sale Price/Date Columns leads fronted to fail to display comps.

E.g. Change line 39 in mainfct.py 

sales_comps = False

to 

sales_comps = True

Any idea why this is?

**Comment by erhla** [comment]
Note that sales comps adds two columns to comps/pin data (Sale Date/Sale Price)

**Comment by austinzhang1018** [comment]
Not sure if this is the only issue, but here's a bug that I found.

Steps for reproducing:
Change line 39 of mainfct.py to True
Launch the program and begin the appeal process with Detroit.
For the address input, input 900 as the street number and anything for the street name. Select the only option

Once you reach the section and attempt to fetch comparables, notice in the console that the json is not properly parsed. I believe this is because, under target pin, Sale Date and Sale Price are NaN, which causes a JSON parse error and for the rest of the program to fail. If there is no sale date/data, I believe you should pass a string instead to prevent this bug, and the rest should work properly.

**Comment by erhla** [comment]
Closed by #f5e266e
